### PR TITLE
WP-3268 Release platform_detect 1.2.0

### PR DESCRIPTION
**Pull request by rmconsole3-wf**
Pulls Included in Release:
* [RAP-1697 Add some simple test utilities for setting the navigators](https://github.com/Workiva/platform_detect/pull/14)

Requested by: @jayudey-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/platform_detect/compare/1.1.1...version-bump-platform_detect-1-2-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/platform_detect/compare/1.1.1...1.2.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by smaifullerton-wk** [comment]
+1

**Comment by bencampbell-wf** [comment]
+1

**Comment by teresarevious-wf** [comment]
RM +1 verified dependencies.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
