### PR TITLE
build with dart base image

### PR DESCRIPTION
**Pull request by josephswanson-wf**
- updating build to use dart base image
- removing unneeded ARGS

Testing: ensure CI passes

@jeffhall-wk @robbecker-wf @Workiva/app-frameworks @bradbenjamin-wf @briansimons-wf

### CODE REVIEW

**Comment by jayudey-wf** [comment]
+1

I'm trying to think if there is ever a reason why we would need to do a dep override here (which would require the ssh credentials), but I can't think of any.

**Comment by jeffhall-wk** [comment]
+1

**Comment by jeffhall-wk** [comment]
+10

- [x] Ensure CI checks pass

**Comment by josephswanson-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
