### PR TITLE
WP-3754 Release platform_detect 1.3.0

### PR DESCRIPTION
**Pull request by rmconsole2-wf**
Pulls Included in Release:
* [UIP-2192 Add browser "feature" detection, and optional CSS class "decorator" functionality](https://github.com/Workiva/platform_detect/pull/16)
* [WP-3898 Utilize travis](https://github.com/Workiva/platform_detect/pull/17)

Requested by: @jayudey-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/platform_detect/compare/1.2.0...version-bump-platform_detect-1-3-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/platform_detect/compare/1.2.0...1.3.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by aaronlademann-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
