### PR TITLE
Enable stricter type checks and fix uses of implicit dynamic

### PR DESCRIPTION
**Pull request by jamesderlin**
Declare explciit types for cases where they won't be inferred so that
they won't be implicitly `dynamic`.

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by jamesderlin** [comment]
Ping? (Maybe @wesleybalvanz-wf ?)

**Comment by evanweible-wf** [comment]
Hi @jamesderlin, thanks for the PR! These changes look good to me, but I had to merge a PR to get our CI running again and it introduced a couple of merge conflicts. Would you mind merging in master and resolving those?

**Comment by jamesderlin** [comment]
> Hi @jamesderlin, thanks for the PR! These changes look good to me, but I had to merge a PR to get our CI running again and it introduced a couple of merge conflicts. Would you mind merging in master and resolving those?

Done.  I accepted the existing upstream versions for the conflicts to my `import` changes.

**Comment by evanweible-wf** [comment]
Looks like we just need to run a `dart format .` on Dart 2.17, then this should be good to go.

**Review by evanweible-wf — APPROVED** [review]

**Comment by evanweible-wf** [comment]
QA +1
@Workiva/release-management-p

**Comment by dancleereman-wf** [comment]
RM +1

**Pull request merged**
