### PR TITLE
WP-3898 Utilize travis

### PR DESCRIPTION
**Pull request by jayudey-wf**
## Issue
- CI wasn't being run

## Changes
**Source:**
- Run the necessary CI steps

**Tests:**
- n/a, purpose of this pr

## Areas of Regression
- failing CI
- the necessary CI tasks aren't being run

## Testing
- passing CI

## Code Review
@aaronlademann-wf @jacehensley-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by rmconsole3-wf** [comment]
Sorry, I could not create a JIRA ticket for this pull.

I sent the following data to JIRA:
`{'issuetype': {'name': None}, 'project': {'key': u'WP'}, 'description': "## Issue\r\n- CI wasn't being run\r\n\r\n## Changes\r\n**Source:**\r\n- Run the necessary CI steps\r\n\r\n**Tests:**\r\n- n/a, purpose of this pr\r\n\r\n## Areas of Regression\r\n- failing CI\r\n- the necessary CI tasks aren't being run\r\n\r\n## Testing\r\n- passing CI\r\n\r\n## Code Review\r\n@aaronlademann-wf @jacehensley-wf ", 'components': [], 'summary': 'Utilize travis'}`

I received the following data from JIRA:
`Hidden on Open Source Repos`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by rmconsole3-wf** [comment]
Sorry, I could not create a JIRA ticket for this pull.

I sent the following data to JIRA:
`{'issuetype': {'name': None}, 'project': {'key': u'WP'}, 'description': "## Issue\r\n- CI wasn't being run\r\n\r\n## Changes\r\n**Source:**\r\n- Run the necessary CI steps\r\n\r\n**Tests:**\r\n- n/a, purpose of this pr\r\n\r\n## Areas of Regression\r\n- failing CI\r\n- the necessary CI tasks aren't being run\r\n\r\n## Testing\r\n- passing CI\r\n\r\n## Code Review\r\n@aaronlademann-wf @jacehensley-wf ", 'components': [], 'summary': 'Utilize travis'}`

I received the following data from JIRA:
`Hidden on Open Source Repos`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by jacehensley-wf** [comment]
+1

**Comment by rm-astro-wf** [comment]
Sorry, I could not create a JIRA ticket for this pull.

I sent the following data to JIRA:
`{'issuetype': {'name': None}, 'project': {'key': u'WP'}, 'description': "## Issue\r\n- CI wasn't being run\r\n\r\n## Changes\r\n**Source:**\r\n- Run the necessary CI steps\r\n\r\n**Tests:**\r\n- n/a, purpose of this pr\r\n\r\n## Areas of Regression\r\n- failing CI\r\n- the necessary CI tasks aren't being run\r\n\r\n## Testing\r\n- passing CI\r\n\r\n## Code Review\r\n@aaronlademann-wf @jacehensley-wf ", 'components': [{'name': u'Task'}], 'summary': 'Utilize travis'}`

I received the following data from JIRA:
`Hidden on Open Source Repos`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by rm-astro-wf** [comment]
Sorry, I could not create a JIRA ticket for this pull.

I sent the following data to JIRA:
`{'issuetype': {'name': u'Task'}, 'project': {'key': u'WP'}, 'description': "## Issue\r\n- CI wasn't being run\r\n\r\n## Changes\r\n**Source:**\r\n- Run the necessary CI steps\r\n\r\n**Tests:**\r\n- n/a, purpose of this pr\r\n\r\n## Areas of Regression\r\n- failing CI\r\n- the necessary CI tasks aren't being run\r\n\r\n## Testing\r\n- passing CI\r\n\r\n## Code Review\r\n@aaronlademann-wf @jacehensley-wf ", 'components': [{'name': u'platform_ticket'}], 'summary': 'Utilize travis'}`

I received the following data from JIRA:
`Hidden on Open Source Repos`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by clairesarsam-wf** [comment]
+1

**Comment by aaronlademann-wf** [comment]
QA +1

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10
- [x] Unit tests created/updated
- [x] All unit tests pass
- [x] Rosie ran/Rosie comment displays expected info
- [x] Dependency Scan Clean

Merging.

**Pull request merged**
