### PR TITLE
CP-2912 Release platform_detect 1.1.1

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [Add license text to distributed files](https://github.com/Workiva/platform_detect/pull/10)
* [Publish to pub.dartlang.org](https://github.com/Workiva/platform_detect/pull/11)

Requested by: @clairesarsam-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/platform_detect/compare/1.1.0...version-bump-platform_detect-1-1-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/platform_detect/compare/1.1.0...1.1.1

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by travissanderson-wf** [comment]
+1

**Comment by clairesarsam-wf** [comment]
This release will be QA +1'd as part of [this PR](https://github.com/Workiva/over_react/pull/40) which brings it into OverReact as a dependency.

**Comment by colefeisthamel-wf** [comment]
RM +1 manually scanned dependencies

**Pull request merged**
